version: "3.8"

services:
  makso_me:
    container_name: maksome
    image: maksome
    env_file:
      - .env.local
    build:
      context: .
      target: production
    ports:
      - "3111:3111"
    restart: unless-stopped
